<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_CheckBox2</name>
   <tag></tag>
   <elementGuidId>cc0cb6f5-49a1-4c94-861e-d0da01ed1ca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;checkboxes&quot;)/input[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='checkboxes']/input[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkboxes&quot;)/input[2]</value>
   </webElementProperties>
</WebElementEntity>
