<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_Checkbox1</name>
   <tag></tag>
   <elementGuidId>6dc1d461-f2d4-4e07-b4cf-ebeb7e6f913d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;checkboxes&quot;)/input[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='checkboxes']/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkboxes&quot;)/input[1]</value>
   </webElementProperties>
</WebElementEntity>
