<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>af81cd0d-4a6c-454c-8fe3-ad6cfcbcdbf4</testSuiteGuid>
   <testCaseLink>
      <guid>0418b68b-0c31-47c4-b6b3-a6b476c4d494</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BasicWebUIExcercise/Tests/UIB_05_VerifyFrames</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05c6ba85-474a-4bc7-822b-ba1b5a23e048</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33852ce4-9b58-4349-a392-a688fcfaa1af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c176bca2-1fe4-4a57-a9ac-ceb7521af159</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1bcfdadb-6287-4d0f-b410-b7c04491ca2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BasicWebUIExcercise/Tests/UIB_07_Verify Key Press</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a22c3c07-13e4-47ab-a8f7-386e01da8eff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BasicWebUIExcercise/Tests/UIB_05_VerifyFrames</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05c6ba85-474a-4bc7-822b-ba1b5a23e048</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33852ce4-9b58-4349-a392-a688fcfaa1af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c176bca2-1fe4-4a57-a9ac-ceb7521af159</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d19939fb-0c8d-412d-aa95-835e381fdf8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BasicWebUIExcercise/Tests/UIB_01_Verify Checkboxes</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>eee3f889-955f-401e-80cf-c99073fef8b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BasicWebUIExcercise/Tests/UIB_03_Verify Dropdown</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc729d75-5f1b-4513-996c-153478e49e90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c2dd57a-27fd-49a8-826c-79b0023e9a90</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b308b6ac-94f0-444a-a1e2-44213c846f16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BasicWebUIExcercise/Tests/UIB_02_Verify Drap And Drop</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0c301262-65c0-4689-9bfb-01e1622c595a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BasicWebUIExcercise/Tests/UIB_09_Verify Slider</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fb121efd-3cb2-4027-a7a8-0c6f053f5dde</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BasicWebUIExcercise/Tests/UIB_10_Verify Menu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44f4dff2-32e1-4c2c-a092-fb8416931f57</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b274909d-357f-4b37-a639-e1d096d36d90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BasicWebUIExcercise/Tests/UIB_04_Verify File Upload</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebebad38-d867-4ca0-85d8-0638d8244863</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>685790b2-4cb7-4f7e-8731-fd76312ea197</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BasicWebUIExcercise/Tests/UIB_06_Verify Alerts</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dfe5fe3-2c69-468a-94ca-2c6200b25737</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90c3b914-4df7-48df-aede-64c3f539603b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BasicWebUIExcercise/Tests/UIB_11_Verify Table</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a439603-18b4-44c3-9563-c8a086903ab5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da3e6f17-9517-4b63-9667-c7b6cf31e172</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1093791-8991-42dc-962e-32e31701ee22</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70b0b1e8-f722-4726-875f-135bfdc33550</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BasicWebUIExcercise/Tests/UIB_08_Verify Color And Font</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
